###
POST http://localhost:9000/login/login
Content-Type: application/json

{   
    
    "username": "saa23456",
    "password": "123"
}

###

POST http://localhost:9000/login/register
Content-Type: application/json

{   
    "username": "saa2346",
    "password": "123"
}
###
GET http://localhost:9000/login/logout



