###
POST http://localhost:9000/login/login
Content-Type: application/json

{   
    
   
    "username": "jonty@a.com",
    "password": "123"
}

###

POST http://localhost:9000/login/register
Content-Type: application/json

{   
    "username": "jonty@a.com",
    "password": "123"
}
###
GET http://localhost:3000/login/logout


###
GET http://localhost:3000/login/sess

###

GET http://localhost:9000/student_profile/60735c9a05c33006340f1d98

###
PATCH http://localhost:9000/student_profile/update/607bcde443b7683b844dcad5/b@a.com
Content-Type: application/json

{
    "name": "yoyo"
    # "phone": "1234567",
    # "stream": "ECE",
    # "section": "A",
    # "year": "3rd",
    # "street": "MG road",
    # "city": "Kolkata",
    # "pin": "700111"

    //: "Web dev"
}

###
GET http://localhost:3000/student_profile/trial

###
GET http://localhost:9000/leave/approved/60819401be83ff3b90a3bed7

###
POST http://localhost:9000/leave/6071d0d388162110b40340eb/souvik
Content-Type: application/json

{   
    "from":"dnvldnvlds",
    "to":"13/34",
    "cause":"fever"
}

###
POST http://localhost:9000/attendence/60819401be83ff3b90a3bed7/jonty@a.com
Content-Type: application/json

{
    "subject":"english"   
}

###
GET  http://localhost:9000/attendence/6071d0d388162110b40340eb


###
GET  http://localhost:9000/admin_viewprofile

###
GET  http://localhost:9000/admin_viewprofile/CSE
###
GET  http://localhost:9000/admin_leave/approved/chatterjeesayak20@gmail.com

###
GET  http://localhost:9000/admin_leave/approve/16


###
GET  http://localhost:9000/admin_leave/view/pending

###
GET http://localhost:9000/admin_attendence/sayak@a.com

###
GET http://localhost:9000/admin_attendence/ed/chatterjeesayak20@gmail.com/trial

###
POST http://localhost:9000/admin_login/a/a_register
Content-Type: application/json

{   "name":"Tohit",
    "username": "ADMIN@a.com",
    "password": "123"
}

###
POST http://localhost:9000/admin_login/a/a_login
Content-Type: application/json

{   
    
    "username": "USER",
    "password": "123"
}

###
GET  http://localhost:9000/admin_login/a/logout

###
POST http://localhost:9000/test
Content-Type: application/json

{
    "name":"Science103",
    "subject":"sc101",
    "questions":[
        {"question": "Trial question","options":[{"A":"hi","B":"hi","C":"hi","D":"hi"}], "ans":"A","marks":5},
        {"question": "Trial question2","options":[{"A":"hi","B":"hi","C":"hi","D":"hi"}], "ans":"A","marks":1},
        {"question": "Trial question2","options":[{"A":"hi","B":"hi","C":"hi","D":"hi"}], "ans":"A","marks":2}
    ]
        
}

###
POST http://localhost:9000/test_respons/31
Content-Type: application/json

{   
    "email":"jonty",
    "answers":["A","B","A"]
}

###
GET  http://localhost:9000/test/32

###
GET  http://localhost:9000/test/endTest/31

###
GET  http://localhost:9000/test_respons/testID/31

###
GET  http://localhost:9000/test_respons/user/jonty

###
GET http://localhost:9000/test/test/live

###
GET http://localhost:9000/test/test/ended

###
GET  http://localhost:9000/file_upload

###
GET  http://localhost:9000/file_upload/getAllFiles





      