###
POST http://localhost:9000/login/login
Content-Type: application/json

{   
    
    "username": "abc",
    "password": "123"
}

###

POST http://localhost:9000/login/register
Content-Type: application/json

{   
    "username": "abc",
    "password": "123"
}
###
GET http://localhost:3000/login/logout


###
GET http://localhost:3000/login/sess

###
GET http://localhost:3000/student_profile

###
PATCH http://localhost:3000/student_profile/update/sayak
Content-Type: application/json

{
    "name": "sayak",
    "phone": "900000000",
    "stream": "CSE",
    "section": "A",
    "year": "3rd",
    "street": "MG road",
    "city": "Kolkata",
    "pin": "700111"

    //: "Web dev"
}

###
GET http://localhost:3000/student_profile/trial

###
GET http://localhost:3000/leave

###
POST http://localhost:3000/leave
Content-Type: application/json

{   
    "from":"12/34",
    "to":"13/34",
    "cause":"fever"
}

###
POST http://localhost:3000/attendence
Content-Type: application/json

{
    "subject":"english"   
}

###
GET  http://localhost:3000/attendence/60661a311dfdb90498a81e53
